apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sample-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /butterscotch
          backend:
            serviceName: butterscotch-service
            servicePort: 5678
        - path: /cinnamon
          backend:
            serviceName: cinnamon-service
            servicePort: 5678